name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      my_name: ${{steps.name_value.outputs.my_name}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: dist
        uses: actions/upload-artifact@v7
        with:
            name: package
            path: dist   #source
      - name: Get a value
        id: name_value
        run: echo 'my_name=Vincent' >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Output build value
        run: echo "name is: ${{needs.build.outputs.my_name}}"
      - name: Get Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: package
      - name: List the files
        run: ls -lrf
      - name: Done with Deployment
        run: echo "Done with deployment"
