name: Output WF
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Repo Name"
        required: true
env:
  VHU: 'Vincent H'
jobs:
    print_name:
      runs-on: ubuntu-latest
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
      steps:
        - name: Display
          run: |
            echo 'The value you entered was ${{inputs.repo_name}}'\
            echo 'Creating Repo...'
        - name: Create Repo
          run: |
            gh repo create ${{inputs.repo_name}} \
              --template "vvvGilead/freeplaneAI" \
              --private \
              --clone
