on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Repo Name"
        required: true
jobs:
    print_name:
      runs-on: ubuntu-latest
      steps:
        - name: Display repo name
          run: |
            echo 'The value you entered was ${{inputs.repo_name}}'
